#!/usr/bin/env python3
"""
Per-clinic environment and secret generation — Aleefy Platform.

The app is single-tenant: one container per clinic, one database per clinic,
one set of secrets per clinic. Nothing here is ever shared between installs.

This module is the only place secrets are created. It is pure enough to test
without PostgreSQL, Docker, or a network (see tests/test_provisioning.py):
generation, rendering, parsing and the merge that makes re-running safe are
plain functions over strings and dicts. The CLI at the bottom is a thin wrapper
that writes one file.

Secrets are written to `<clinic-dir>/.env` with mode 0600 and printed ONCE by
provision.sh. They are never logged, never echoed into a shell history line,
and never passed on a command line (argv is world-readable via `ps`).

Windows note: os.chmod cannot express POSIX 0600 on Windows. The CLI says so
loudly instead of pretending. Provisioning is a Linux-production operation;
on Windows this module is importable and testable but should not be used to
create a real clinic.
"""
from __future__ import annotations

import argparse
import os
import re
import secrets
import string
import sys
from pathlib import Path

# ── The secret surface ───────────────────────────────────────────────────────
# Derived from a full grep of `os.environ.get(` across the Python tree.
# Anything here that already has a value in an existing .env is PRESERVED on a
# re-run — regenerating PLATFORM_SECRET_KEY logs every user out, regenerating
# POSTGRES_DSN orphans the clinic from its own records.

# Generated by us, one unique value per install.
GENERATED_SECRETS = (
    "PLATFORM_SECRET_KEY",   # Flask session signing key (config.py)
    "PLATFORM_ADMIN_PASS",   # first-run admin seed (config.py SEED_ADMIN_PASS)
    "POSTGRES_DSN",          # carries the per-clinic PostgreSQL password
    "WAITING_ROOM_TOKEN",    # public TV display gate (blueprints/appointments)
    "API_V1_KEY",            # Bearer token for /api/v1 (blueprints/api_v1)
)

# Supplied by the operator when the clinic buys the feature. Never generated,
# always preserved across re-runs so an upgrade does not wipe a paid API key.
OPERATOR_SECRETS = (
    "AI_API_KEY",
    "GOOGLE_API_KEY",
    "WAPILOT_TOKEN",
    "WAPILOT_INSTANCE",
    "BACKUP_S3_KEY",
    "BACKUP_S3_SECRET",
    "BACKUP_S3_BUCKET",
    "BACKUP_S3_ENDPOINT",
    "BACKUP_S3_REGION",
    "BACKUP_S3_PREFIX",
    "SENTRY_DSN",
)

PRESERVED_ON_UPGRADE = GENERATED_SECRETS + OPERATOR_SECRETS

# Characters that survive .env parsing, docker-compose interpolation, and a
# copy-paste into a shell, without quoting: no space, no quote, no '#',
# no '$' (compose expands it), no backslash, no backtick.
_SAFE_SPECIALS = "!@%^*_-+=?."
_PW_ALPHABET = string.ascii_letters + string.digits + _SAFE_SPECIALS
# DSN passwords stay alphanumeric so the URL never needs percent-encoding.
_DSN_ALPHABET = string.ascii_letters + string.digits

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$")

DEFAULT_PORT_BASE = 5100
DEFAULT_PORT_LIMIT = 5300


# ── Generation ───────────────────────────────────────────────────────────────

def gen_secret_key() -> str:
    """128 hex chars. config.ProductionConfig.validate() needs >= 32."""
    return secrets.token_hex(64)


def gen_token(nbytes: int = 32) -> str:
    """URL-safe token for WAITING_ROOM_TOKEN / API_V1_KEY."""
    return secrets.token_urlsafe(nbytes)


def gen_db_password(length: int = 32) -> str:
    """Alphanumeric only — goes inside a postgresql:// URL verbatim."""
    return "".join(secrets.choice(_DSN_ALPHABET) for _ in range(length))


def gen_admin_password(length: int = 20) -> str:
    """A password that passes models.security.validate_password_strength.

    That validator wants >= 12 chars with upper, lower, digit and special. A
    plain random draw satisfies it ~always but not certainly, and "~always" is
    how a provisioning run fails at 11pm. Force one of each class, then shuffle.
    """
    if length < 12:
        raise ValueError("admin password must be at least 12 characters")
    chars = [
        secrets.choice(string.ascii_uppercase),
        secrets.choice(string.ascii_lowercase),
        secrets.choice(string.digits),
        secrets.choice(_SAFE_SPECIALS),
    ]
    chars += [secrets.choice(_PW_ALPHABET) for _ in range(length - len(chars))]
    # secrets.SystemRandom().shuffle — random.shuffle is not cryptographic.
    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


def build_dsn(user: str, password: str, host: str, port: int, dbname: str,
              sslmode: str = "") -> str:
    """app.py matches postgresql://user:pass@host:port/dbname — keep that shape.

    A DSN that does not match falls back to SQLite *silently*, which is how a
    clinic ends up running on an empty local file nobody backs up.
    """
    dsn = f"postgresql://{user}:{password}@{host}:{port}/{dbname}"
    if sslmode:
        dsn += f"?sslmode={sslmode}"
    return dsn


def generate_secrets(*, db_user: str, db_host: str, db_port: int,
                     db_name: str, sqlite: bool = False,
                     sslmode: str = "") -> dict[str, str]:
    """One fresh, unique value for every generated secret."""
    return {
        "PLATFORM_SECRET_KEY": gen_secret_key(),
        "PLATFORM_ADMIN_PASS": gen_admin_password(),
        "POSTGRES_DSN": "" if sqlite else build_dsn(
            db_user, gen_db_password(), db_host, db_port, db_name, sslmode),
        "WAITING_ROOM_TOKEN": gen_token(24),
        "API_V1_KEY": gen_token(32),
    }


# ── .env read / write ────────────────────────────────────────────────────────

def parse_env(text: str) -> dict[str, str]:
    """KEY=VALUE lines. Comments and blanks ignored, surrounding quotes dropped."""
    out: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if key:
            out[key] = value
    return out


_ENV_HEADER = """\
# ══════════════════════════════════════════════════════════════════════
#  Aleefy — clinic: {slug}
#  Generated by scripts/provision/provision.sh on {stamp}
#
#  THIS FILE CONTAINS LIVE SECRETS. mode 0600. Never commit it, never copy
#  it to another clinic, never paste it into a chat or a ticket.
#  To rotate a secret: edit the one line, then restart the clinic.
# ══════════════════════════════════════════════════════════════════════
"""


def render_env(values: dict[str, str], slug: str, stamp: str) -> str:
    """Deterministic .env text. Secrets last, so an operator scrolling past
    the config does not shoulder-surf them by accident."""
    secret_keys = [k for k in values if k in PRESERVED_ON_UPGRADE]
    plain_keys = [k for k in values if k not in PRESERVED_ON_UPGRADE]
    lines = [_ENV_HEADER.format(slug=slug, stamp=stamp), ""]
    for key in sorted(plain_keys):
        lines.append(f"{key}={values[key]}")
    lines += ["", "# ── secrets — unique to this clinic ──"]
    for key in sorted(secret_keys):
        lines.append(f"{key}={values[key]}")
    return "\n".join(lines) + "\n"


def write_env(path: Path, text: str) -> list[str]:
    """Write 0600. Returns a list of warnings (empty on a healthy POSIX write)."""
    warnings: list[str] = []
    path.parent.mkdir(parents=True, exist_ok=True)
    # Create with the right mode from the start: writing then chmod leaves a
    # window where the secrets are world-readable.
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        os.write(fd, text.encode("utf-8"))
    finally:
        os.close(fd)
    if os.name == "nt":
        warnings.append(
            f"{path} was written without POSIX permissions (Windows). Its "
            "secrets are readable by every account on this machine. Provision "
            "real clinics on Linux.")
    else:
        mode = path.stat().st_mode & 0o777
        if mode != 0o600:
            warnings.append(f"{path} is mode {mode:o}, expected 600")
    return warnings


# ── Idempotency ──────────────────────────────────────────────────────────────

def install_state(clinic_dir: Path) -> str:
    """'absent' | 'partial' | 'present'.

    'partial' is a provisioning run that died halfway — the directory exists but
    there is no .env, so there is nothing to lose by continuing.
    """
    if (clinic_dir / ".env").is_file():
        return "present"
    if clinic_dir.exists() and any(clinic_dir.iterdir()):
        return "partial"
    return "absent"


class InstallExists(Exception):
    """Raised instead of overwriting a live clinic."""


def plan(state: str, upgrade: bool) -> str:
    """Decide what a provisioning run is allowed to do. Never 'overwrite'.

    absent/partial          -> 'create'  (fresh secrets)
    present + --upgrade     -> 'upgrade' (keep every existing secret)
    present without flag    -> refuse, loudly
    """
    if state == "present":
        if not upgrade:
            raise InstallExists(
                "This clinic is already provisioned (.env exists). Re-running "
                "would replace its session key, admin password and database "
                "password, locking the clinic out of its own records.\n"
                "  To refresh non-secret config and keep the secrets: "
                "add --upgrade\n"
                "  To rotate one secret: edit that line in .env and restart.\n"
                "  To start over from empty: move the clinic directory aside "
                "first, deliberately.")
        return "upgrade"
    return "create"


def merge_env(existing: dict[str, str], fresh: dict[str, str]) -> dict[str, str]:
    """Fresh config wins; existing secrets win. Empty is not a value.

    An operator-supplied secret that exists but is blank (placeholder line) is
    treated as unset, so a later run can still fill it in.
    """
    merged = dict(fresh)
    for key, value in existing.items():
        if key in PRESERVED_ON_UPGRADE and value.strip():
            merged[key] = value
        elif key not in fresh:
            # Hand-added lines (a custom PLATFORM_TAGLINE, an extra var) survive.
            merged[key] = value
    return merged


# ── Port allocation ──────────────────────────────────────────────────────────

def taken_ports(root: Path) -> dict[int, str]:
    """host-port -> clinic slug, read from every provisioned .env under root."""
    out: dict[int, str] = {}
    clinics = root / "clinics"
    if not clinics.is_dir():
        return out
    for env_file in sorted(clinics.glob("*/.env")):
        try:
            values = parse_env(env_file.read_text(encoding="utf-8"))
        except OSError as exc:
            print(f"warning: cannot read {env_file}: {exc}", file=sys.stderr)
            continue
        raw = values.get("CLINIC_HOST_PORT", "")
        if raw.isdigit():
            out[int(raw)] = env_file.parent.name
    return out


def next_port(taken: dict[int, str] | set[int], base: int = DEFAULT_PORT_BASE,
              limit: int = DEFAULT_PORT_LIMIT) -> int:
    """Lowest free port at or above base."""
    for port in range(base, limit):
        if port not in taken:
            return port
    raise ValueError(
        f"no free host port in {base}..{limit}. That is ~{limit - base} clinics "
        "on one host, far past what this shape supports — split the VPS.")


# ── Full environment ─────────────────────────────────────────────────────────

def build_env(*, slug: str, domain: str, host_port: int, secrets_map: dict[str, str],
              app_image: str, sqlite: bool = False,
              title: str = "", emergency_phone: str = "",
              app_version: str = "1.0.0") -> dict[str, str]:
    """Every var this clinic's container needs. Secrets come in pre-generated."""
    env = {
        # ── identity ──
        "CLINIC_SLUG": slug,
        "PLATFORM_TITLE": title or slug.replace("-", " ").title(),
        "PLATFORM_ADMIN_USER": "admin",
        # ── stage ──
        "FLASK_ENV": "production",
        "PLATFORM_DEBUG": "0",
        "SESSION_COOKIE_SECURE": "1" if domain else "0",
        "LOG_LEVEL": "INFO",
        # ── networking ──
        # PLATFORM_PORT is the port INSIDE the container (gunicorn.conf.py binds
        # it). CLINIC_HOST_PORT is what the host maps to it — different things,
        # and conflating them is why a clinic silently answers on the wrong port.
        "PLATFORM_PORT": "5100",
        "CLINIC_HOST_PORT": str(host_port),
        "CORS_ALLOWED_ORIGIN": f"https://{domain}" if domain else "",
        "CORS_ALLOW_WILDCARD": "0",
        # ── storage (container paths; ./data and ./logs are bind-mounted) ──
        "PLATFORM_DB_PATH": "/app/data/platform.db",
        "BACKUP_OFFSITE_DIR": "",
        "BACKUP_STALE_DAYS": "2",
        # ── image / version, read back by the inventory ──
        "APP_IMAGE": app_image,
        "APP_VERSION": app_version,
        # ── legacy desktop app is not deployed per clinic ──
        "LEGACY_APP_ENABLED": "0",
        "EMERGENCY_PHONE": emergency_phone,
    }
    if sqlite:
        # ponytail: SQLite single-clinic mode has no separate DB server to lose,
        # which is the point on a clinic PC. Ceiling: one box, no read replica,
        # backups are the only copy. Move to PostgreSQL when the clinic wants
        # off-site standby.
        env["POSTGRES_DSN"] = ""
    env.update(secrets_map)
    return env


# ── CLI ──────────────────────────────────────────────────────────────────────

def _cmd_print_value(args) -> int:
    """Read one value out of an .env without shell-quoting bugs.

    Used by provision.sh to feed the DB password to psql over stdin. The value
    goes to stdout for command substitution — never into argv, which `ps` shows
    to every user on the box.
    """
    values = parse_env(Path(args.env_file).read_text(encoding="utf-8"))
    value = values.get(args.print_value)
    if value is None:
        print(f"{args.print_value} not found in {args.env_file}", file=sys.stderr)
        return 1
    print(value)
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate a clinic .env")
    p.add_argument("--clinic-dir", help="target directory (contains .env)")
    p.add_argument("--slug")
    p.add_argument("--domain", default="")
    p.add_argument("--title", default="")
    p.add_argument("--emergency-phone", default="")
    p.add_argument("--db-host", default="127.0.0.1")
    p.add_argument("--db-port", type=int, default=5432)
    p.add_argument("--db-name", default="")
    p.add_argument("--db-user", default="")
    p.add_argument("--sslmode", default="")
    p.add_argument("--host-port", type=int, default=0)
    p.add_argument("--app-image", default="aleefy:latest")
    p.add_argument("--app-version", default="1.0.0")
    p.add_argument("--sqlite", action="store_true")
    p.add_argument("--upgrade", action="store_true")
    p.add_argument("--print-value", metavar="KEY",
                   help="print one value from --env-file and exit")
    p.add_argument("--env-file")
    args = p.parse_args(argv)

    if args.print_value:
        if not args.env_file:
            p.error("--print-value needs --env-file")
        return _cmd_print_value(args)

    for required in ("clinic_dir", "slug"):
        if not getattr(args, required):
            p.error(f"--{required.replace('_', '-')} is required")
    if not SLUG_RE.match(args.slug):
        p.error(f"bad slug {args.slug!r}: use 3-32 chars of a-z, 0-9 and '-'")

    clinic_dir = Path(args.clinic_dir)
    try:
        action = plan(install_state(clinic_dir), args.upgrade)
    except InstallExists as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2

    env_path = clinic_dir / ".env"
    existing = (parse_env(env_path.read_text(encoding="utf-8"))
                if action == "upgrade" else {})

    db_name = args.db_name or f"clinic_{args.slug.replace('-', '_')}"
    db_user = args.db_user or db_name
    host_port = args.host_port or int(existing.get("CLINIC_HOST_PORT") or 0) \
        or next_port(taken_ports(clinic_dir.parent.parent))

    fresh = build_env(
        slug=args.slug,
        domain=args.domain,
        host_port=host_port,
        secrets_map=generate_secrets(
            db_user=db_user, db_host=args.db_host, db_port=args.db_port,
            db_name=db_name, sqlite=args.sqlite, sslmode=args.sslmode),
        app_image=args.app_image,
        sqlite=args.sqlite,
        title=args.title,
        emergency_phone=args.emergency_phone,
        app_version=args.app_version,
    )
    final = merge_env(existing, fresh) if action == "upgrade" else fresh

    from datetime import datetime, timezone
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    for warning in write_env(env_path, render_env(final, args.slug, stamp)):
        print(f"WARNING: {warning}", file=sys.stderr)

    # Machine-readable, secret-free: provision.sh reads this to decide whether
    # it still needs to CREATE the database role.
    print(f"ACTION={action}")
    print(f"DB_NAME={db_name}")
    print(f"DB_USER={db_user}")
    print(f"HOST_PORT={final['CLINIC_HOST_PORT']}")
    print(f"NEW_SECRETS={'yes' if action == 'create' else 'no'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
