#!/usr/bin/env python3
"""
Aleefy front-end asset build. Pure stdlib — no npm, no node, no bundler.

    python static/css/build.py            # build
    python static/css/build.py --check    # verify build is current (CI/pre-commit)

What it does
------------
1.  Regenerates  static/css/icons.css   — a bootstrap-icons subset containing
    only the `bi-*` icons actually referenced by templates/ and static/js/.
2.  Concatenates + minifies the CSS sources into  static/css/app.min.css
    and the JS sources into  static/js/app.min.js.
3.  Rewrites the ASSET_V literal in templates/base.html with a content hash,
    so a deploy can never serve stale CSS from a browser cache.

RE-RUN THIS AFTER EDITING ANY FILE IN sources[]  — the readable sources are
what you edit; the .min.* files are build output.

ponytail: hand-rolled regex minifier instead of a real CSS parser. It handles
this codebase (no `content:"/*"` strings, no legacy IE hacks) and is verified
by check() below. Ceiling: it is NOT a general-purpose minifier. If someone
adds CSS with a comment sequence inside a quoted string, or relies on the
`>>>`/`/deep/` combinators, swap in `csscompressor`/`rcssmin` (pure-python,
pip-installable, no node) rather than growing this function.
"""
import hashlib, os, re, sys

ROOT     = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CSS_DIR  = os.path.join(ROOT, "static", "css")
JS_DIR   = os.path.join(ROOT, "static", "js")
FONT_DIR = os.path.join(ROOT, "static", "fonts")
BASE_TPL = os.path.join(ROOT, "templates", "base.html")

# Order matters — this IS the cascade. tokens.css must come first.
CSS_SOURCES = ["tokens.css", "icons.css", "platform.css", "aleefy.css", "v3.css"]
JS_SOURCES  = ["platform.js", "v3.js"]


# ── 1. bootstrap-icons subset ────────────────────────────────────────────
def build_icons_css():
    """Emit icons.css with @font-face + only the bi-* codepoints in use.

    ponytail: subset over shipping all 2050 icon rules (98 KB raw / 66 KB
    minified) on every page. Ceiling: adding `<i class="bi bi-new-thing">` to
    a template renders NOTHING until this script is re-run. That is the whole
    cost of the subset. If icon churn ever becomes annoying, delete the
    `used` filter below and ship the full map.
    """
    src = os.path.join(FONT_DIR, "_bootstrap-icons-src.css")
    if not os.path.exists(src):
        print("  ! %s missing - keeping existing icons.css" % src)
        return
    raw = open(src, encoding="utf-8").read()
    codepoints = dict(re.findall(r'\.(bi-[a-z0-9-]+)::before\s*\{\s*content:\s*"([^"]+)"', raw))

    used = set()
    for base in (os.path.join(ROOT, "templates"), JS_DIR):
        for dp, _, fns in os.walk(base):
            for fn in fns:
                if fn.endswith((".html", ".js")):
                    body = open(os.path.join(dp, fn), encoding="utf-8", errors="replace").read()
                    used |= set(re.findall(r"\bbi-[a-z0-9-]+", body))
    hit = sorted(used & set(codepoints))

    out = ["/* GENERATED by static/css/build.py - do not edit by hand.",
           "   bootstrap-icons v1.11.3 (MIT) - self-hosted subset.",
           "   %d of %d icons, matching the bi-* classes used in templates/." % (len(hit), len(codepoints)),
           "   Re-run `python static/css/build.py` after adding a new icon. */",
           "@font-face{font-display:block;font-family:bootstrap-icons;"
           "src:url('../fonts/bootstrap-icons.woff2') format('woff2')}",
           '.bi::before,[class^="bi-"]::before,[class*=" bi-"]::before{'
           "display:inline-block;font-family:bootstrap-icons!important;font-style:normal;"
           "font-weight:normal!important;font-variant:normal;text-transform:none;line-height:1;"
           "vertical-align:-.125em;-webkit-font-smoothing:antialiased;"
           "-moz-osx-font-smoothing:grayscale}"]
    out += ['.%s::before{content:"%s"}' % (n, codepoints[n]) for n in hit]
    open(os.path.join(CSS_DIR, "icons.css"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    missing = sorted(used - set(codepoints) - {"bi-"})
    print("  icons.css: %d icons kept (of %d available)%s"
          % (len(hit), len(codepoints),
             ("; %d unknown bi-* token(s) ignored: %s" % (len(missing), ", ".join(missing[:6]))) if missing else ""))


# ── 2. minifiers ─────────────────────────────────────────────────────────
def minify_css(src):
    """Whitespace + comment stripping only. Deliberately conservative.

    NOT stripped around `+`: `calc(100% + 20px)` becomes invalid without the
    spaces. NOT rewriting anything inside parens: an earlier version added a
    space after `not(`/`and(` "to be safe" and silently killed every
    `:not(...)` selector in the bundle. Whitespace is the only safe edit here.
    """
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)   # comments
    src = re.sub(r"\s+", " ", src)                     # collapse whitespace
    src = re.sub(r"\s*([{}:;,>~])\s*", r"\1", src)     # around safe punctuation
    src = re.sub(r";\s*}", "}", src)                   # trailing semicolons
    return src.strip()


def selectors(css):
    """Crude selector extraction — used by check_minifier() to prove the
    minified bundle still contains every rule the sources declared."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out, depth, buf = [], 0, ""
    for ch in css:
        if ch == "{":
            if depth == 0:
                s = buf.strip()
                if s and not s.startswith("@"):
                    out.append(re.sub(r"\s+", " ", s))
            depth += 1; buf = ""
        elif ch == "}":
            depth -= 1; buf = ""
        else:
            buf += ch
    return out


def check_minifier(raw, mini):
    """Self-check: minifying must not lose or mangle a single selector.

    This exists because it already happened once — `:not(...)` selectors were
    silently dropped, which is invisible until someone notices a hover state
    is gone. Runs on every build; a mismatch aborts.
    """
    a = [re.sub(r"\s*([,>~])\s*", r"\1", s) for s in selectors(raw)]
    b = [re.sub(r"\s*([,>~])\s*", r"\1", s) for s in selectors(mini)]
    if a != b:
        lost = [s for s in a if s not in b][:10]
        sys.exit("MINIFIER BUG: %d selectors in, %d out. Missing/mangled: %s"
                 % (len(a), len(b), lost))


def minify_js(src):
    """Conservative: strip only full-line // comments, /* */ blocks and blank
    lines. Does NOT collapse lines — statement-level rewriting of hand-written
    JS without a parser is how you ship a production outage at 3am.
    ponytail: line-level only. Ceiling: ~30% savings instead of ~60%. If that
    matters more than the risk, add `rjsmin` (pure python, pip) — not a bundler.
    """
    out, in_block = [], False
    for line in src.split("\n"):
        s = line.strip()
        if in_block:
            if "*/" in s:
                in_block = False
                s = s.split("*/", 1)[1].strip()
                if not s: continue
            else:
                continue
        if s.startswith("/*"):
            if "*/" not in s:
                in_block = True
                continue
            s = re.sub(r"/\*.*?\*/", "", s).strip()
        if not s or s.startswith("//"):
            continue
        out.append(s)
    return "\n".join(out)


# ── 3. build ─────────────────────────────────────────────────────────────
def bundle(dirpath, sources, minifier, kind):
    parts = []
    for name in sources:
        p = os.path.join(dirpath, name)
        if not os.path.exists(p):
            print("  ! skipping missing %s" % name); continue
        raw = open(p, encoding="utf-8").read()
        mini = minifier(raw)
        if kind == "css":
            check_minifier(raw, mini)          # aborts the build on regression
        parts.append("/* %s */" % name)
        parts.append(mini)
    return "\n".join(parts) + "\n"


def build(check_only=False):
    if not check_only:
        build_icons_css()

    css = bundle(CSS_DIR, CSS_SOURCES, minify_css, "css")
    js  = bundle(JS_DIR,  JS_SOURCES,  minify_js,  "js")
    version = hashlib.sha256((css + js).encode("utf-8")).hexdigest()[:10]

    css_out = os.path.join(CSS_DIR, "app.min.css")
    js_out  = os.path.join(JS_DIR,  "app.min.js")
    base    = open(BASE_TPL, encoding="utf-8").read()
    new_base = re.sub(r'(\{%\s*set\s+ASSET_V\s*=\s*")[0-9a-f]*(")', r"\g<1>%s\g<2>" % version, base, count=1)
    if new_base == base and "ASSET_V" not in base:
        sys.exit("ERROR: base.html has no `{% set ASSET_V = \"...\" %}` line to stamp.")

    if check_only:
        stale = [n for n, want, path in
                 (("app.min.css", css, css_out), ("app.min.js", js, js_out), ("base.html", new_base, BASE_TPL))
                 if not os.path.exists(path) or open(path, encoding="utf-8").read() != want]
        if stale:
            sys.exit("STALE: %s — run `python static/css/build.py`" % ", ".join(stale))
        print("build is current (v=%s)" % version)
        return

    for path, data in ((css_out, css), (js_out, js), (BASE_TPL, new_base)):
        open(path, "w", encoding="utf-8", newline="\n").write(data)

    raw_css = sum(os.path.getsize(os.path.join(CSS_DIR, n)) for n in CSS_SOURCES if os.path.exists(os.path.join(CSS_DIR, n)))
    raw_js  = sum(os.path.getsize(os.path.join(JS_DIR, n))  for n in JS_SOURCES  if os.path.exists(os.path.join(JS_DIR, n)))
    print("  app.min.css  %7d -> %7d bytes (%.0f%% smaller, %d files -> 1)"
          % (raw_css, len(css.encode()), 100 * (1 - len(css.encode()) / raw_css), len(CSS_SOURCES)))
    print("  app.min.js   %7d -> %7d bytes (%.0f%% smaller, %d files -> 1)"
          % (raw_js, len(js.encode()), 100 * (1 - len(js.encode()) / raw_js), len(JS_SOURCES)))
    print("  base.html    ASSET_V = %s" % version)


if __name__ == "__main__":
    build(check_only="--check" in sys.argv)
