# -*- coding: utf-8 -*-
"""Generate the vectors that scripts/verify_phone_tool.js checks the phone against.

The Python is the reference implementation - it is what the app itself uses to
verify a code, so if the two ever disagree, the Python is right by definition
and the phone is wrong.

    python scripts/verify_phone_tool.py     # writes scripts/license_vectors.json
    node   scripts/verify_phone_tool.js     # checks the phone against it

The masters here are fixed test strings, deliberately. Never put a real master
secret in this file - scripts/license_vectors.json is committed.
"""
import json
import os
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models import licensing as lic     # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "license_vectors.json")

# Test masters. Not secrets - the point is that both sides agree on the maths.
MASTERS = ["test-master-alpha", "another-master-99", "m"]
CLINICS = ["hatem-vet", "cairo-north", "x", "عيادة-حاتم"]
MACHINES = ["77064095", "00000000", "99999999", "12345678"]
EXPIRIES = [date(2027, 8, 31), date(2026, 12, 31), date(2030, 1, 31),
            date(2028, 2, 29)]           # a leap February, on purpose


def _plus_one_year() -> date:
    t = date.today()
    return lic._end_of_month(t.year + 1, t.month)


def main():
    codes, secrets_ = [], []

    for m in MASTERS:
        for c in CLINICS:
            s = lic.derive_clinic_secret(m, c)
            secrets_.append({"master": m, "clinic": c, "secret": s})
            for machine in MACHINES:
                for exp in EXPIRIES:
                    codes.append({
                        "master": m,
                        "clinic": c,
                        "machine": machine,
                        "expiry": exp.isoformat(),
                        "code": lic.make_code(s.encode("utf-8"), machine, exp),
                    })

    data = {
        "note": "Generated by scripts/verify_phone_tool.py. Test data only.",
        "plus_one_year": _plus_one_year().isoformat(),
        "secrets": secrets_,
        "codes": codes,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=1)

    print("wrote %d code vectors and %d secret vectors to %s"
          % (len(codes), len(secrets_), os.path.basename(OUT)))
    print("now run:  node scripts/verify_phone_tool.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
