"""
Clinical Decision Support (CDS) — Aleefy Platform
=================================================

Species contraindications, drug-drug interactions and weight-based dose ranges.

WHAT THIS MODULE IS
-------------------
A deterministic rule engine over ONE curated, cited, human-reviewable data file
(``drug_data.json``, sitting next to this file). Every clinical fact shown to a
user comes from that file. Nothing is generated by a language model at runtime,
so the module works with the AI service switched off, offline, or unreachable.

WHAT THIS MODULE IS NOT
-----------------------
It is not authoritative and it is not complete. See ``_KNOWN_GAPS`` in the data
file. Absence of a warning NEVER means "safe" — an unrecognised drug produces a
loud ``unverified`` alert instead of silence.

The engine (everything above the "Flask routes" banner) is pure: no database, no
network, no Flask context. It is unit-testable on its own — see
``tests/test_cds.py``.
"""

import json
import os
import re
from dataclasses import dataclass, field, asdict
from decimal import Decimal, InvalidOperation, getcontext
from typing import Optional

from flask import render_template, request, jsonify

from . import cds_bp
from blueprints.auth.routes import login_required


# ═════════════════════════════════════════════════════════════════════════════
#  Data file
# ═════════════════════════════════════════════════════════════════════════════

_DATA_PATH = os.path.join(os.path.dirname(__file__), "drug_data.json")


def _load(path=_DATA_PATH):
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)

    # Normalise dose rows once so the engine has one shape to deal with. Insulin
    # is dosed in IU/kg rather than mg/kg; a vet adding another such drug just
    # sets "units" and "min_units_per_kg" / "max_units_per_kg".
    for row in data["doses"]:
        # "units" is the unit of the drug itself, not of the per-kg rate. A row
        # written "IU/kg" would otherwise label the TOTAL as IU/kg and double the
        # suffix on the per-kg line ("0.25-0.5 IU/kg/kg").
        unit = (row.get("units") or "mg").split("/")[0].strip() or "mg"
        row["unit"] = unit
        row["min_per_kg"] = row.get("min_mg_per_kg") or row.get("min_units_per_kg")
        row["max_per_kg"] = row.get("max_mg_per_kg") or row.get("max_units_per_kg")
        row["max_per_kg_per_day"] = (
            row.get("max_mg_per_kg_per_day") or row.get("max_units_per_kg_per_day")
        )
    return data


DATA = _load()

ADVISORY = DATA["advisory"]
DATA_VERSION = DATA["version"]
REVIEW_STATUS = DATA["review_status"]

_CLASSES = DATA["drug_classes"]
_ALIASES = DATA["aliases"]
_SPECIES_ALIASES = DATA["species_aliases"]
_WEIGHT_RANGES = DATA["species_weight_range_kg"]

# Longest alias key, in tokens — bounds the n-gram scan in _resolve_drug.
_MAX_ALIAS_TOKENS = max(len(k.split()) for k in _ALIASES)


def _class_coverage_gaps():
    """Members of a drug class that no interaction rule can reach.

    An interaction written against ``gentamicin`` does not extend to its
    aminoglycoside siblings, so screening tobramycin is silently narrower than
    screening gentamicin. The engine cannot invent the missing rules — the
    clinical facts are not in the data file — but it can refuse to be silent
    about the hole. Maps member -> (class, siblings that DO have rules).
    """
    named = {k for e in DATA["interactions"] for k in e["drugs"]}
    gaps = {}
    for cls, members in _CLASSES.items():
        if cls in named:
            continue                       # the class itself is screened
        covered = sorted(m for m in members if m in named)
        if covered:
            gaps.update({m: (cls, covered) for m in members if m not in named})
    return gaps


_CLASS_GAPS = _class_coverage_gaps()


# ═════════════════════════════════════════════════════════════════════════════
#  Severity
# ═════════════════════════════════════════════════════════════════════════════

CONTRAINDICATED = "contraindicated"
MAJOR = "major"
UNVERIFIED = "unverified"   # not in the database — the vet must check manually
MODERATE = "moderate"
CAUTION = "caution"
INFO = "info"

# Sort order for the UI. UNVERIFIED deliberately outranks MODERATE: "we do not
# know" is a bigger deal than a known, managed, moderate interaction.
SEVERITY_RANK = {
    CONTRAINDICATED: 0,
    MAJOR: 1,
    UNVERIFIED: 2,
    MODERATE: 3,
    CAUTION: 4,
    INFO: 5,
}

SEVERITY_LABEL = {
    CONTRAINDICATED: {"en": "DO NOT GIVE", "ar": "ممنوع الإعطاء"},
    MAJOR:           {"en": "Major risk",  "ar": "خطر كبير"},
    UNVERIFIED:      {"en": "Not in database — verify manually",
                      "ar": "غير موجود في قاعدة البيانات — تحقق يدويًا"},
    MODERATE:        {"en": "Moderate",    "ar": "خطر متوسط"},
    CAUTION:         {"en": "Caution",     "ar": "تنبيه"},
    INFO:            {"en": "Note",        "ar": "ملاحظة"},
}


@dataclass
class Alert:
    """One thing the prescriber needs to know. Never constructed from AI output."""
    severity: str
    kind: str                      # contraindication | breed | interaction | dose | lookup
    drugs: list                    # display names, as the user typed them
    message_en: str
    message_ar: str
    species: Optional[str] = None
    alternative_en: str = ""
    alternative_ar: str = ""
    source: str = ""

    @property
    def rank(self):
        return SEVERITY_RANK.get(self.severity, 9)

    def to_dict(self):
        d = asdict(self)
        d["severity_label"] = SEVERITY_LABEL.get(self.severity, SEVERITY_LABEL[INFO])
        return d


@dataclass
class DoseResult:
    ok: bool
    drug: str                       # as supplied
    species: str                    # as supplied
    canonical: Optional[str] = None
    weight_kg: Optional[str] = None
    unit: str = "mg"
    min_total: Optional[str] = None     # per administration, for this patient
    max_total: Optional[str] = None
    max_daily_total: Optional[str] = None
    per_kg_range: str = ""
    frequency: str = ""
    route: str = ""
    note_en: str = ""
    note_ar: str = ""
    source: str = ""
    refusal_en: str = ""
    refusal_ar: str = ""
    alerts: list = field(default_factory=list)

    def to_dict(self):
        d = asdict(self)
        d["alerts"] = [a.to_dict() if isinstance(a, Alert) else a for a in self.alerts]
        return d


# ═════════════════════════════════════════════════════════════════════════════
#  Name matching
#
#  Deliberately EXACT, never fuzzy. Inventory rows are trade names with
#  strengths, dosage forms and sometimes Arabic ("Synulox 250mg Tablets",
#  "باراسيتامول 500 مجم"). We strip the packaging noise and then require an
#  exact hit in the alias table. A near-miss produces an `unverified` alert, not
#  a guess: a wrong match that silently fails to warn is the dangerous outcome,
#  and edit-distance matching would confuse e.g. prednisone/prednisolone and
#  amikacin/amoxicillin.
# ═════════════════════════════════════════════════════════════════════════════

# Packaging / formulation noise. Removed before matching.
_NOISE = {
    "mg", "mcg", "ug", "gm", "gr", "iu", "ml", "l", "kg", "cc", "unit", "units",
    "tab", "tabs", "tablet", "tablets", "cap", "caps", "capsule", "capsules",
    "susp", "suspension", "syrup", "solution", "soln", "sol", "elixir",
    "inj", "injection", "injectable", "vial", "ampoule", "amp", "amps",
    "cream", "ointment", "gel", "paste", "powder", "sachet", "drops", "drop",
    "spray", "collar", "shampoo", "chew", "chewable", "chews", "flavour",
    "flavor", "flavoured", "flavored", "spot", "spoton", "topical",
    "oral", "po", "sc", "iv", "im", "otm", "sq",
    "for", "and", "plus", "with", "the", "per", "pack", "box", "strip",
    "dog", "dogs", "cat", "cats", "puppy", "puppies", "kitten", "kittens",
    "small", "medium", "large", "extra", "forte", "vet", "veterinary",
    "بيطري", "أقراص", "اقراص", "قرص", "شراب", "حقن", "مجم", "مل", "معلق",
    "للكلاب", "للقطط", "كبسولات", "مرهم",
}

_NUMERIC = re.compile(r"^[\d.,/x×+-]+[a-z%]*$")
_NON_WORD = re.compile(r"[^0-9a-z؀-ۿ%]+")


def _basic_clean(raw: str) -> str:
    """Lowercase and drop punctuation. Nothing else — used for species and breed,
    where the drug noise list would eat the actual word ("cat", "dog")."""
    if not raw:
        return ""
    return " ".join(_NON_WORD.sub(" ", str(raw).lower()).split())


def clean_name(raw: str) -> str:
    """Lowercase, drop punctuation, strengths and dosage-form words. Drugs only."""
    tokens = [
        tok for tok in _basic_clean(raw).split()
        if tok not in _NOISE and not _NUMERIC.match(tok)
    ]
    return " ".join(tokens)


@dataclass
class DrugMatch:
    raw: str
    canonicals: list          # 0 = unknown, 1 = confident, >1 = combination product
    reason: str               # matched | combination | unknown | empty

    @property
    def ok(self):
        return bool(self.canonicals)


def resolve_drug(raw: str) -> DrugMatch:
    """Map a free-text / inventory drug name onto canonical keys.

    Longest n-gram wins, so "amoxicillin clavulanic acid" resolves to the
    combination product rather than to plain amoxicillin. If several distinct
    canonical drugs match at that length the name is treated as a COMBINATION
    product and all of them are screened — over-warning is the safe direction.
    """
    cleaned = clean_name(raw)
    if not cleaned:
        return DrugMatch(raw, [], "empty")

    tokens = cleaned.split()
    for n in range(min(_MAX_ALIAS_TOKENS, len(tokens)), 0, -1):
        hits = []
        for i in range(len(tokens) - n + 1):
            canonical = _ALIASES.get(" ".join(tokens[i:i + n]))
            if canonical and canonical not in hits:
                hits.append(canonical)
        if hits:
            return DrugMatch(raw, hits, "matched" if len(hits) == 1 else "combination")

    return DrugMatch(raw, [], "unknown")


def resolve_species(raw: str) -> Optional[str]:
    cleaned = _basic_clean(raw)
    if not cleaned:
        return None
    if cleaned in _SPECIES_ALIASES:
        return _SPECIES_ALIASES[cleaned]
    for tok in cleaned.split():
        if tok in _SPECIES_ALIASES:
            return _SPECIES_ALIASES[tok]
    return None


def _drug_in(entry_key: str, canonical: str) -> bool:
    """True if `canonical` is the entry's drug, or a member of its drug class."""
    return entry_key == canonical or canonical in _CLASSES.get(entry_key, ())


def _unknown_drug_alert(raw: str) -> Alert:
    return Alert(
        severity=UNVERIFIED,
        kind="lookup",
        drugs=[raw],
        message_en=(
            f'"{raw}" is NOT in the clinical database. No contraindication, '
            f"interaction or dose check has been performed for it. This is not a "
            f"statement that it is safe — check a current formulary manually."
        ),
        message_ar=(
            f'الدواء "{raw}" غير موجود في قاعدة البيانات السريرية. لم يتم إجراء أي '
            f"فحص لموانع الاستعمال أو التداخلات أو الجرعة. هذا لا يعني أنه آمن — "
            f"يجب المراجعة يدويًا في مرجع دوائي حديث."
        ),
    )


# ═════════════════════════════════════════════════════════════════════════════
#  Rule engine — pure functions
# ═════════════════════════════════════════════════════════════════════════════

def check_contraindications(drug: str, species: str, breed: str = None) -> list:
    """Species- and breed-specific 'do not give' rules for a single drug."""
    alerts = []
    match = resolve_drug(drug)
    sp = resolve_species(species)

    if not match.ok:
        return [_unknown_drug_alert(drug)]

    if match.reason == "combination":
        alerts.append(Alert(
            severity=INFO, kind="lookup", drugs=[drug],
            message_en=("Read as a combination product containing: "
                        + ", ".join(match.canonicals)
                        + ". Each component was screened separately — confirm this is correct."),
            message_ar=("تمت قراءته كمستحضر مركّب يحتوي على: "
                        + "، ".join(match.canonicals)
                        + ". فُحص كل مكوّن على حدة — يُرجى التأكد من صحة ذلك."),
        ))

    if sp is None:
        alerts.append(Alert(
            severity=UNVERIFIED, kind="lookup", drugs=[drug], species=species,
            message_en=(f'Species "{species or "(blank)"}" was not recognised, so NO '
                        f"species contraindication check was performed. Species-specific "
                        f"lethality is the most important check this tool does — set the "
                        f"species on the patient record and re-run."),
            message_ar=(f'لم يتم التعرف على النوع "{species or "(فارغ)"}"، لذلك لم يُجرَ أي '
                        f"فحص لموانع الاستعمال حسب النوع. يُرجى ضبط نوع الحيوان في ملف "
                        f"المريض وإعادة الفحص."),
        ))
        return alerts

    breed_clean = _basic_clean(breed)

    for canonical in match.canonicals:
        for entry in DATA["species_contraindications"]:
            if _drug_in(entry["drug"], canonical) and sp in entry["species"]:
                alerts.append(Alert(
                    severity=entry["severity"], kind="contraindication",
                    drugs=[drug], species=sp,
                    message_en=entry["effect"]["en"], message_ar=entry["effect"]["ar"],
                    alternative_en=entry.get("alternative", {}).get("en", ""),
                    alternative_ar=entry.get("alternative", {}).get("ar", ""),
                    source=entry["source"],
                ))

        for entry in DATA["breed_contraindications"]:
            if not (_drug_in(entry["drug"], canonical) and sp in entry["species"]):
                continue
            # Both sides through _basic_clean: the typed breed is stripped of
            # punctuation, so a rule string like "long-haired whippet" could
            # never match "Long-haired Whippet" while only one side was cleaned.
            hit = ([b for b in entry["breeds"] if _basic_clean(b) in breed_clean]
                   if breed_clean else [])
            if hit:
                alerts.append(Alert(
                    severity=entry["severity"], kind="breed",
                    drugs=[drug], species=sp,
                    message_en=(f"Breed \"{breed}\" is on the at-risk list "
                                f"({entry.get('gene') or 'breed predisposition'}). "
                                + entry["effect"]["en"]),
                    message_ar=(f"السلالة \"{breed}\" ضمن السلالات المعرّضة للخطر "
                                f"({entry.get('gene') or 'استعداد سلالي'}). "
                                + entry["effect"]["ar"]),
                    alternative_en=entry.get("alternative", {}).get("en", ""),
                    alternative_ar=entry.get("alternative", {}).get("ar", ""),
                    source=entry["source"],
                ))
            elif not breed_clean:
                alerts.append(Alert(
                    severity=CAUTION, kind="breed", drugs=[drug], species=sp,
                    message_en=(f"No breed recorded for this patient. {canonical} has a "
                                f"breed-specific contraindication "
                                f"({entry.get('gene') or 'breed predisposition'}) — "
                                f"confirm the breed before prescribing."),
                    message_ar=(f"لم تُسجَّل سلالة هذا المريض. للدواء {canonical} مانع استعمال "
                                f"مرتبط بالسلالة — يجب تأكيد السلالة قبل الوصف."),
                    source=entry["source"],
                ))

    return sorted(alerts, key=lambda a: a.rank)


def check_interactions(drug_list) -> list:
    """Pairwise interaction screen over a list of drug names."""
    alerts = []
    matches = [resolve_drug(d) for d in (drug_list or []) if str(d).strip()]

    for m in matches:
        if not m.ok:
            alerts.append(_unknown_drug_alert(m.raw))

    resolved = [m for m in matches if m.ok]

    # Same active ingredient prescribed twice (e.g. a trade name and a generic).
    seen = {}
    for m in resolved:
        for canonical in m.canonicals:
            if canonical in seen and seen[canonical] != m.raw:
                alerts.append(Alert(
                    severity=MAJOR, kind="interaction",
                    drugs=[seen[canonical], m.raw],
                    message_en=(f'"{seen[canonical]}" and "{m.raw}" are both {canonical} — '
                                f"duplicate therapy. The patient would receive a double dose."),
                    message_ar=(f'"{seen[canonical]}" و"{m.raw}" كلاهما {canonical} — '
                                f"ازدواج علاجي؛ سيتلقى المريض ضعف الجرعة."),
                ))
            seen.setdefault(canonical, m.raw)

    # Only worth saying when an interaction screen actually happened.
    if len(resolved) > 1:
        for m in resolved:
            for canonical in m.canonicals:
                cls, covered = _CLASS_GAPS.get(canonical, (None, None))
                if not cls:
                    continue
                alerts.append(Alert(
                    severity=CAUTION, kind="lookup", drugs=[m.raw],
                    message_en=(f"{canonical} is in the {cls} class, but no interaction "
                                f"rule in this dataset is written against that class — "
                                f"only against {', '.join(covered)} individually. The "
                                f"interactions recorded for those drugs have NOT been "
                                f"checked for {canonical}. Check them manually."),
                    message_ar=(f"ينتمي {canonical} إلى فئة {cls}، لكن لا توجد في هذه "
                                f"البيانات قاعدة تداخل مكتوبة على مستوى الفئة — بل على "
                                f"أدوية بعينها ({'، '.join(covered)}). لم تُفحص التداخلات "
                                f"المسجَّلة لتلك الأدوية بالنسبة لـ {canonical} — يجب "
                                f"مراجعتها يدويًا."),
                ))

    for i in range(len(resolved)):
        for j in range(i + 1, len(resolved)):
            a, b = resolved[i], resolved[j]
            for ca in a.canonicals:
                for cb in b.canonicals:
                    for entry in DATA["interactions"]:
                        k1, k2 = entry["drugs"]
                        forward = _drug_in(k1, ca) and _drug_in(k2, cb)
                        reverse = _drug_in(k1, cb) and _drug_in(k2, ca)
                        if not (forward or reverse):
                            continue
                        if k1 == k2 and ca == cb:
                            continue  # a class-vs-itself rule needs two different members
                        alerts.append(Alert(
                            severity=entry["severity"], kind="interaction",
                            drugs=[a.raw, b.raw],
                            message_en=entry["effect"]["en"],
                            message_ar=entry["effect"]["ar"],
                            source=entry["source"],
                        ))

    # De-duplicate: the same rule can fire twice via a class and a member.
    unique, keys = [], set()
    for al in alerts:
        key = (al.severity, al.kind, tuple(sorted(al.drugs)), al.message_en[:80])
        if key not in keys:
            keys.add(key)
            unique.append(al)
    return sorted(unique, key=lambda a: a.rank)


def _dec(value):
    """Parse a caller-supplied number, or None if it is not one the engine can
    compute on. "nan" and "inf" parse cleanly and then raise InvalidOperation on
    the first comparison or quantize; a magnitude past the working precision
    cannot be rounded for display and would render millions of digits. Both are
    rejected here rather than reaching the arithmetic — a 500 is not a refusal.
    """
    try:
        d = Decimal(str(value).strip())
    except (InvalidOperation, AttributeError, ValueError):
        return None
    return d if d.is_finite() and d.adjusted() < getcontext().prec else None


def _fmt(d: Decimal) -> str:
    """Trim a Decimal for display without going anywhere near float."""
    try:
        d = d.quantize(Decimal("0.0001"))
    except InvalidOperation:
        pass    # more digits than the context can round — print it whole, not 500
    return format(d.normalize(), "f")


# No animal a veterinary clinic treats weighs more than this. The bound is
# about catching a typed extra zero, not about zoology.
MAX_BODY_WEIGHT_KG = 2000


def calculate_dose(drug: str, species: str, weight_kg, breed: str = None) -> DoseResult:
    """Weight-based dose range for one drug in one patient.

    Refuses rather than extrapolates: an unknown drug, an unknown species, a
    drug/species pair with no entry, or a drug that is contraindicated in this
    patient all return ok=False with a reason.
    All arithmetic is Decimal — a rounding error here has physical consequences.
    """
    match = resolve_drug(drug)
    sp = resolve_species(species)
    weight = _dec(weight_kg)

    def refuse(en, ar, alerts=None):
        return DoseResult(ok=False, drug=drug, species=species,
                          canonical=match.canonicals[0] if match.ok else None,
                          refusal_en=en, refusal_ar=ar, alerts=alerts or [])

    if not match.ok:
        return refuse(
            f'"{drug}" is not in the clinical database, so no dose can be calculated. '
            f"Never extrapolate a dose from another drug or another species.",
            f'الدواء "{drug}" غير موجود في قاعدة البيانات، ولا يمكن حساب الجرعة. '
            f"لا يجوز إطلاقًا اشتقاق الجرعة من دواء آخر أو نوع آخر.",
            [_unknown_drug_alert(drug)],
        )
    if match.reason == "combination":
        return refuse(
            f'"{drug}" was read as a combination product ({", ".join(match.canonicals)}). '
            f"Dose each active ingredient separately from the product label.",
            f'تمت قراءة "{drug}" كمستحضر مركّب ({"، ".join(match.canonicals)}). '
            f"يجب حساب جرعة كل مادة فعّالة على حدة من نشرة المستحضر.",
        )
    if sp is None:
        return refuse(
            f'Species "{species or "(blank)"}" is not recognised. Dose ranges are '
            f"species-specific and are never carried across species.",
            f'النوع "{species or "(فارغ)"}" غير معروف. مدى الجرعات يختلف حسب النوع '
            f"ولا يُنقل بين الأنواع.",
        )
    # Before any number is produced. A dose card printed under a DO NOT GIVE
    # card reads as an instruction; the guard belongs here rather than in the
    # template so /api/dose cannot serve one either.
    blocked = [a for a in check_contraindications(drug, species, breed)
               if a.severity == CONTRAINDICATED]
    if blocked:
        return refuse(
            f'"{drug}" is contraindicated in this patient, so no dose is calculated. '
            f"A drug that must not be given has no safe dose.",
            f'الدواء "{drug}" ممنوع الإعطاء لهذا المريض، لذلك لم تُحسب أي جرعة. '
            f"الدواء الممنوع ليس له جرعة آمنة.",
            blocked,
        )
    # An upper bound as well as a lower one. Removing the crash on an absurd
    # weight is only half the fix: 1e24 kg stopped raising and started
    # returning 1e23 mg as a real dose card, which is worse than an error -
    # an error is obviously wrong, a printed number looks considered.
    # 2000 kg clears every patient a mixed practice sees, a draught horse
    # included, and a typed extra zero above that is a slip, not a patient.
    if weight is None or weight <= 0 or weight > MAX_BODY_WEIGHT_KG:
        return refuse(
            f'Weight "{weight_kg}" is not a usable body weight in kg.',
            f'الوزن "{weight_kg}" غير صالح كوزن جسم بالكيلوجرام.',
        )

    canonical = match.canonicals[0]
    row = next((r for r in DATA["doses"]
                if r["drug"] == canonical and r["species"] == sp), None)
    if row is None:
        return refuse(
            f"No dose entry for {canonical} in {sp}. This tool will not extrapolate a "
            f"dose from another species — use a current formulary.",
            f"لا توجد جرعة مسجلة لـ {canonical} في {sp}. لن تُشتق الجرعة من نوع آخر — "
            f"يُرجى الرجوع إلى مرجع دوائي حديث.",
        )

    alerts = []
    rng = _WEIGHT_RANGES.get(sp)
    if rng:
        low, high = _dec(rng["min"]), _dec(rng["max"])
        if weight < low or weight > high:
            alerts.append(Alert(
                severity=MAJOR, kind="dose", drugs=[drug], species=sp,
                message_en=(f"{weight_kg} kg is outside the plausible weight range for a "
                            f"{sp} ({rng['min']}-{rng['max']} kg). Check the weight and the "
                            f"units before giving this dose — a mis-keyed weight is a "
                            f"common cause of overdose."),
                message_ar=(f"الوزن {weight_kg} كجم خارج المدى المنطقي لهذا النوع ({sp}: "
                            f"{rng['min']}-{rng['max']} كجم). تحقق من الوزن ووحدته قبل "
                            f"الإعطاء — خطأ إدخال الوزن سبب شائع لفرط الجرعة."),
            ))

    min_pk, max_pk = _dec(row["min_per_kg"]), _dec(row["max_per_kg"])
    max_daily_pk = _dec(row.get("max_per_kg_per_day"))

    return DoseResult(
        ok=True, drug=drug, species=species, canonical=canonical,
        weight_kg=_fmt(weight), unit=row["unit"],
        min_total=_fmt(min_pk * weight),
        max_total=_fmt(max_pk * weight),
        max_daily_total=_fmt(max_daily_pk * weight) if max_daily_pk is not None else None,
        per_kg_range=(f"{row['min_per_kg']}-{row['max_per_kg']} {row['unit']}/kg"
                      if row["min_per_kg"] != row["max_per_kg"]
                      else f"{row['min_per_kg']} {row['unit']}/kg"),
        frequency=row.get("frequency", ""), route=row.get("route", ""),
        note_en=row.get("note", {}).get("en", ""),
        note_ar=row.get("note", {}).get("ar", ""),
        source=row["source"], alerts=alerts,
    )


def screen(drugs, species, breed=None, weight_kg=None) -> dict:
    """Full screen for a prescription: contraindications + interactions + doses."""
    drugs = [str(d).strip() for d in (drugs or []) if str(d).strip()]
    alerts = []
    for d in drugs:
        alerts.extend(check_contraindications(d, species, breed))
    alerts.extend(check_interactions(drugs))

    # Same alert can arrive from two drugs in a combination product.
    unique, keys = [], set()
    for al in alerts:
        key = (al.severity, al.kind, tuple(sorted(al.drugs)), al.message_en[:80])
        if key not in keys:
            keys.add(key)
            unique.append(al)
    unique.sort(key=lambda a: a.rank)

    doses = [calculate_dose(d, species, weight_kg, breed) for d in drugs] if weight_kg else []

    return {
        "drugs": drugs,
        "species": species,
        "breed": breed,
        "weight_kg": weight_kg,
        "alerts": unique,
        "doses": doses,
        "worst_severity": unique[0].severity if unique else None,
        "checked_count": len(drugs),
        "unrecognised": [m.raw for m in (resolve_drug(d) for d in drugs) if not m.ok],
        "advisory": ADVISORY,
        "data_version": DATA_VERSION,
        "review_status": REVIEW_STATUS,
    }


# ═════════════════════════════════════════════════════════════════════════════
#  Flask routes
# ═════════════════════════════════════════════════════════════════════════════

def _parse_drugs(value):
    """Accept a JSON list, or newline/comma-separated free text from the form."""
    if isinstance(value, (list, tuple)):
        return [str(v) for v in value]
    return [p for p in re.split(r"[\n,;]+", str(value or ""))]


def _result_json(result):
    out = dict(result)
    out["alerts"] = [a.to_dict() for a in result["alerts"]]
    out["doses"] = [d.to_dict() for d in result["doses"]]
    return out


@cds_bp.route("/", methods=["GET", "POST"])
@login_required
def index():
    """Standalone manual checker. Server-rendered — works without JavaScript."""
    result = None
    form = {"drugs": "", "species": "", "breed": "", "weight_kg": ""}
    if request.method == "POST":
        form = {
            "drugs": request.form.get("drugs", ""),
            "species": request.form.get("species", ""),
            "breed": request.form.get("breed", ""),
            "weight_kg": request.form.get("weight_kg", "").strip(),
        }
        # Rendered from the plain-dict form so the template sees the same shape
        # the JSON endpoint returns — one representation, not two.
        result = _result_json(screen(
            _parse_drugs(form["drugs"]), form["species"],
            form["breed"] or None, form["weight_kg"] or None,
        ))
    return render_template(
        "cds/index.html", active="cds", form=form, result=result,
        severity_rank=SEVERITY_RANK, severity_label=SEVERITY_LABEL,
        advisory=ADVISORY, data_version=DATA_VERSION, review_status=REVIEW_STATUS,
    )


@cds_bp.route("/api/screen", methods=["POST"])
@login_required
def api_screen():
    """JSON screen. Callable from the visits / pharmacy prescribing flows.

    POST {"drugs": ["Metacam 1.5mg/ml", "Prednisolone"], "species": "Cat",
          "breed": "Persian", "weight_kg": "4.2"}

    Send the CSRF token in the X-CSRF-Token header (app.py validates every
    non-GET request). Response mirrors screen() with alerts sorted worst-first.
    """
    data = request.get_json(silent=True) or {}
    result = screen(
        _parse_drugs(data.get("drugs")),
        data.get("species", ""),
        data.get("breed") or None,
        data.get("weight_kg") or None,
    )
    return jsonify(_result_json(result))


@cds_bp.route("/api/dose", methods=["POST"])
@login_required
def api_dose():
    """JSON dose calculation for a single drug. Refuses rather than extrapolates."""
    data = request.get_json(silent=True) or {}
    res = calculate_dose(data.get("drug", ""), data.get("species", ""),
                         data.get("weight_kg"), data.get("breed") or None)
    out = res.to_dict()
    out["advisory"] = ADVISORY
    return jsonify(out)
